package server.assets;

public enum RequestType {
	
	LOGIN,
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	SIGNUP,
	SIGN_UP_SUCCESS,
	SIGN_UP_FAILED,
	SEND_INVITATION,
	RECEIVE_INVITATION,
	ACCEPT_INVITATION,
	REJECT_INVITATION,
	CHAT,
	SEND_REPLY,
	RECEIVE_REPLY,
	SEND_MSG,
	SEND_MOVE,
	RECEIVE_MOVE,
	RECEIVE_MSG,
    ONLINE_PLAYERS,
	END_GAME,
    END_SESSION,
    MULTI_GAME,
	
}
